baseURL = "https://suonewlook.github.io/"
languageCode = "zh-cn"
title = "纯人类写作基地"
theme = "stack"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS"]

[params.sidebar]
  emoji = ""
  subtitle = "思考慢慢"

[params]
  mainSections = ["posts"]

[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.png"

[params.widgets]
  homepage = [
    { type = "search" },
    { type = "archives" },
    { type = "tag-cloud" }
  ]
  page = [
    { type = "toc" }
  ]

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "现在"
    url = "/now/"
    weight = 5
