baseURL = "https://suonewlook.github.io/"
languageCode = "zh-cn"
title = "纯人类写作基地"
theme = "stack"
hasCJKLanguage = true

[pagination]
  pagerSize = 10
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.png"
